var annotated_dup =
[
    [ "_GPU_DEVICE", "struct___g_p_u___d_e_v_i_c_e.html", "struct___g_p_u___d_e_v_i_c_e" ],
    [ "Aodv", "class_aodv.html", "class_aodv" ],
    [ "Aodv_message", "class_aodv__message.html", "class_aodv__message" ],
    [ "Aodv_rerr", "class_aodv__rerr.html", "class_aodv__rerr" ],
    [ "Aodv_route", "class_aodv__route.html", "class_aodv__route" ],
    [ "Aodv_rrep", "class_aodv__rrep.html", "class_aodv__rrep" ],
    [ "Aodv_rreq", "class_aodv__rreq.html", "class_aodv__rreq" ],
    [ "AodvTest", "class_aodv_test.html", "class_aodv_test" ],
    [ "BaseStation", "class_base_station.html", "class_base_station" ],
    [ "Basic", "class_basic.html", "class_basic" ],
    [ "Basic_addressed", "class_basic__addressed.html", "class_basic__addressed" ],
    [ "Basic_addressed_message", "class_basic__addressed__message.html", "class_basic__addressed__message" ],
    [ "Basic_message", "class_basic__message.html", "class_basic__message" ],
    [ "BasicAddrTest", "class_basic_addr_test.html", "class_basic_addr_test" ],
    [ "BasicTest", "class_basic_test.html", "class_basic_test" ],
    [ "CommMod", "class_comm_mod.html", "class_comm_mod" ],
    [ "Coord", "struct_coord.html", "struct_coord" ],
    [ "Drone", "class_drone.html", "class_drone" ],
    [ "Dummy_comm", "class_dummy__comm.html", "class_dummy__comm" ],
    [ "Dummy_program", "class_dummy__program.html", "class_dummy__program" ],
    [ "Element", "class_element.html", "class_element" ],
    [ "Environment", "class_environment.html", "class_environment" ],
    [ "GLFWgammaramp", "struct_g_l_f_wgammaramp.html", "struct_g_l_f_wgammaramp" ],
    [ "GLFWimage", "struct_g_l_f_wimage.html", "struct_g_l_f_wimage" ],
    [ "GLFWvidmode", "struct_g_l_f_wvidmode.html", "struct_g_l_f_wvidmode" ],
    [ "IpAllocator", "class_ip_allocator.html", "class_ip_allocator" ],
    [ "Message", "class_message.html", "class_message" ],
    [ "Messageable", "class_messageable.html", "class_messageable" ],
    [ "ParrotTest", "class_parrot_test.html", "class_parrot_test" ],
    [ "SensingBaseStation", "class_sensing_base_station.html", "class_sensing_base_station" ],
    [ "SensingDrone", "class_sensing_drone.html", "class_sensing_drone" ]
];