var annotated_dup =
[
    [ "Aodv", "class_aodv.html", "class_aodv" ],
    [ "Aodv_message", "class_aodv__message.html", "class_aodv__message" ],
    [ "Aodv_rerr", "class_aodv__rerr.html", "class_aodv__rerr" ],
    [ "Aodv_route", "class_aodv__route.html", "class_aodv__route" ],
    [ "Aodv_rrep", "class_aodv__rrep.html", "class_aodv__rrep" ],
    [ "Aodv_rreq", "class_aodv__rreq.html", "class_aodv__rreq" ],
    [ "AodvComms", "class_aodv_comms.html", "class_aodv_comms" ],
    [ "BaseStation", "class_base_station.html", "class_base_station" ],
    [ "Basic", "class_basic.html", "class_basic" ],
    [ "Basic_addressed", "class_basic__addressed.html", "class_basic__addressed" ],
    [ "Basic_message", "class_basic__message.html", "class_basic__message" ],
    [ "Basic_message_addressed", "class_basic__message__addressed.html", "class_basic__message__addressed" ],
    [ "CommMod", "class_comm_mod.html", "class_comm_mod" ],
    [ "Coord", "struct_coord.html", "struct_coord" ],
    [ "Drone", "class_drone.html", "class_drone" ],
    [ "Environment", "class_environment.html", "class_environment" ],
    [ "IpAllocator", "class_ip_allocator.html", "class_ip_allocator" ],
    [ "Message", "class_message.html", "class_message" ],
    [ "Messageable", "class_messageable.html", "class_messageable" ],
    [ "SensingBaseStation", "class_sensing_base_station.html", "class_sensing_base_station" ],
    [ "SensingDrone", "class_sensing_drone.html", "class_sensing_drone" ],
    [ "Test", "class_test.html", "class_test" ]
];